[core]
	######   For Windows   ######
	;sshCommand = 'C:\\windows\\System32\\OpenSSH\\ssh.exe'
	;editor = 'C:\\Users\\d.sprehe\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code' --wait
	;autocrlf = true
	######   For Msys2   ######
	;sshCommand = 'C:\\msys64\\usr\\bin\\ssh.exe'
	;editor = 'C:\\Users\\d.sprehe\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code' --wait
	;autocrlf = true
	######   For WSL   ######
	;sshCommand = /usr/bin/ssh
	;editor = 'code' --wait
	;autocrlf = input
	######   For Linux   ######
	;sshCommand = /usr/bin/ssh
	;editor = ''
	;autocrlf = input
	######   For Mac   ######
	;sshCommand = /usr/bin/ssh
	;editor = ''
	;autocrlf = input
	######   For BSD   ######
	;sshCommand = /usr/bin/ssh
	;editor = ''
	;autocrlf = input
[alias]
	br = branch
	brsc = branch --show-current
	cf = config
	cfg = config --global
	ck = "!fnc() { if [ $# -gt 1 ]; then git co $@; else git co $1 -q && echo \"Switched to branch '$(git brsc)'\" && git st; fi; }; fnc; unset -f fnc"
	co = checkout
	cm = commit -m
	pick = cherry-pick
	df = diff HEAD
	dfu = diff
	dfs = diff --staged
	graph = log --graph --decorate --full-diff --stat --patch
	lg = log --oneline --decorate
	mgff = merge --ff-only
	mg = merge
	pl = pull
	ps = push
	rb = rebase
	rbff = rebase --ff-only
	rs = reset
	st = "!fnc() { if [ $# -gt 0 ]; then git status \"$@\"; else git status -sbu && stls=$(git stash list | wc -l); if [ $stls -ne 0 ]; then echo \"$: $stls\"; fi; unset stls; fi; }; fnc; unset -f fnc"
	stat = status --branch --untracked-files --show-stash
	sw = "!fnc() { if [ $# -gt 1 ]; then git swc $@; else git swc $1 -q && echo \"Switched to branch '$(git brsc)'\" && git st; fi; }; fnc; unset -f fnc"
	swc = switch
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
[user]
	name = Church1776
	email = brassmajor@gmail.com
[init]
	defaultBranch = master
[log]
	